name: fancy_flags
description: This is a fancy package for Flutter that allows you to use PNG flags in your app.

maintainer: Gökhan Çavuş
homepage: https://github.com/gokhancvs/fancy_flags
repository: https://github.com/gokhancvs/fancy_flags
issue_tracker: https://github.com/gokhancvs/fancy_flags/issues

version: 1.0.3

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - assets/png/
